# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ACGTN2num <- function(nv, cv, ncores) {
    invisible(.Call('_LDWeaver_ACGTN2num', PACKAGE = 'LDWeaver', nv, cv, ncores))
}

.fastHadamard <- function(MIt, den, uq_t, pxy_t, pxpy_t, RXY, pXrX, pYrY, ncores) {
    invisible(.Call('_LDWeaver_fastHadamard', PACKAGE = 'LDWeaver', MIt, den, uq_t, pxy_t, pxpy_t, RXY, pXrX, pYrY, ncores))
}

.compareToRow <- function(x, y) {
    .Call('_LDWeaver_compareToRow', PACKAGE = 'LDWeaver', x, y)
}

.vecPosMatch <- function(x, y) {
    .Call('_LDWeaver_vecPosMatch', PACKAGE = 'LDWeaver', x, y)
}

.compareTriplet <- function(MI0X, MI0Z, MI0) {
    .Call('_LDWeaver_compareTriplet', PACKAGE = 'LDWeaver', MI0X, MI0Z, MI0)
}

.fast_intersect <- function(A, B) {
    .Call('_LDWeaver_fast_intersect', PACKAGE = 'LDWeaver', A, B)
}

.extractAlnParam <- function(file, filter, gap_thresh, maf_thresh) {
    .Call('_LDWeaver_extractAlnParam', PACKAGE = 'LDWeaver', file, filter, gap_thresh, maf_thresh)
}

.extractSNPs <- function(file, n_seq, n_snp, POS) {
    .Call('_LDWeaver_extractSNPs', PACKAGE = 'LDWeaver', file, n_seq, n_snp, POS)
}

.extractRef <- function(file) {
    .Call('_LDWeaver_extractRef', PACKAGE = 'LDWeaver', file)
}

.readFasta <- function(file, pos_len) {
    .Call('_LDWeaver_readFasta', PACKAGE = 'LDWeaver', file, pos_len)
}

